        .data                   
             
prompt1:  .asciiz "Enter the number of elements (max 100): "
prompt2:  .asciiz "Enter element: "
menu:     .asciiz "\nMenu:\n1. Find max\n2. Count max occurrences\n3. Count divisible by max\n4. Quit\nEnter choice: "
maxMsg:   .asciiz "Maximum number: "
countMsg: .asciiz "Occurrences of max: "
divMsg:   .asciiz "Number of elements that can divide max: "
quitMsg:  .asciiz "Quitting...\n"

	.align 4
array:  .space 800

  	.text
	.globl main
	
main:
	li $v0, 4
	la $a0, prompt1
	syscall
	li $v0, 5               
        syscall
        move $t0, $v0	  
        move $t1, $zero
        
get_elems:
	bge $t1, $t0, menu_loop
	
	li $v0, 4
	la $a0, prompt2
	syscall
	
	li $v0, 5
	syscall
	
	sll $t2, $t1, 2
	la $t3, array
	add $t3, $t3, $t2
	sw $v0, 0($t3)                            
	
	addi $t1, $t1, 1
	j get_elems

menu_loop:
	
	li $v0, 4
	la $a0, menu
	syscall
		                	                	                	                
	li $v0, 5
	syscall
	move $t4, $v0
	
	beq $t4, 1, find_max
	beq $t4, 2, count_max
	beq $t4, 3, div_max
	beq $t4, 4, exit
	j menu_loop   

find_max:
	li $t5, 0
	li $t1, 0

max_loop:
	bge $t1, $t0, print_max
	
	sll $t2, $t1, 2
	la $t3, array
	add $t3, $t3, $t2
	lw $t6, 0($t3)
	
	ble $t6, $t5, next_max
	move $t5, $t6
next_max:
	addi $t1, $t1, 1
	j max_loop
print_max:
	li $v0, 4
	la $a0, maxMsg
	syscall
	
	li $v0,1
	move $a0, $t5
	syscall
	j menu_loop
					
count_max:
	li $t7, 0
	li $t1, 0
	
count_loop:
	bge $t1, $t0, print_count
																																																																												
	sll $t2, $t1, 2
	la $t3, array
	add $t3, $t3, $t2
	lw $t6, 0($t3)
	addi $t1, $t1, 1
	beq $t6, $t5, increment
	
	j count_loop	 	 	 	 	 	 	 	 
           
increment:
	addi $t7, $t7, 1
	j count_loop

print_count:
	li $v0, 4
	la $a0, countMsg
	syscall
	
	li $v0, 1
	move $a0, $t7
	syscall
	j menu_loop	

div_max:	
	li $t8, 0
	li $t1, 0
	
div_max_loop:
	bge $t1, $t0, print_div
	
	sll $t2, $t1, 2
	la $t3, array
	add $t3, $t3, $t2
	lw $t6, 0($t3)
	addi $t1, $t1, 1
	
	beq $t6, $t5, div_max_loop
	div $t5, $t6
	mfhi $t7
	
	beq $t7, $zero, increment_div																																																																				
	j div_max_loop																																																																																																																																								
																																																																																																																																																																																																													
increment_div:
	addi $t8, $t8, 1
	j div_max_loop																																																																																																																																																																																																																																																																																	
																																																																																																																																																																																																																																																																																																																																																					
print_div:
	li $v0, 4
	la $a0, divMsg
	syscall
																																																																																																																																																																																																																																																																																																																																																																																																																										
	li $v0, 1
	move $a0, $t8
	syscall
	j menu_loop																																																																																																																																																																																																																																																																																																																																																																																																																																																																																												
																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																	
exit: 
	li $v0, 4
	la $a0, quitMsg
	syscall
																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																							
	li $v0, 10
	syscall																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																								
																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																													
																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																	
																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																					
																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																									
																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																													
																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																	
																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																					
																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																									
																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																													
																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																	
																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																					
																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																									
																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																													
																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																	
																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																					
																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																									
																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																													
																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																	
																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																					
																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																									
																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																													
																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																	
																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																					
																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																									
																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																													
																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																	
																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																					
																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																													